[project]
name = "doranbori-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google>=3.0.0",
    "ipykernel>=6.30.1",
    "numpy>=2.3.4",
    "scipy>=1.16.3",
    "torch>=2.9.0",
]
